### ISSUE TITLE
How can I send AT Command via serial port??

### ISSUE THREAD

**Issue by mahdi-gh1373** [node-serialport/node-serialport#1408]
- __SerialPort Version__:latest
- __NodeJS Version__:v8.8.1
- __Operating System__ and __Hardware Platform__: Quectel

- Have you checked the right __version__ of the __api docs?__:yes
- Are you having trouble installing and you checked the __Installation Special Cases__ docs?
- Are you using __Electron__ and have you checked the _Electron Docs_?:yes

### Summary of Problem
I need to send some AT Command via my ttyUSB3 serial port??

**Comment by gauthamkantharaju** [comment]
Create a buffer as below,

var at_cmd = new Buffer("AT\r"); and write,

serialport.write(at_cmd, function(err) {
  if(err) {
    return console.log("AT command write error " + err);
  }
});
