### ISSUE TITLE
Failed to install serialport on beaglebone black

### ISSUE THREAD

**Issue by sdhouib** [node-serialport/node-serialport#1425]
- __SerialPort Version__: 6.0.4
- __NodeJS Version__: 6.2.2
- __Operating System__ and __Hardware Platform__: Debian , arm processor, beaglebone black

- Have you checked the right __version__ of the __api docs?__: yes
- Are you having trouble installing and you checked the __Installation Special Cases__ docs? yes
- Are you using __Electron__ and have you checked the _Electron Docs_?: no

### Summary of Problem
I tried to install serialport using this command: 
sudo npm install serialport --unsafe-perm --build-from-source
An extract of the error log is below:
../src/serialport.cpp:25:1: warning: control reaches end of non-void function [-
Wreturn-type]
../src/serialport.cpp: In function 'int getIntFromObject(v8::Local<v8::Object>,
std::string)':
../src/serialport.cpp:21:1: warning: control reaches end of non-void function [-
Wreturn-type]
../src/serialport.cpp: In function 'v8::Local<v8::Value> getValueFromObject(v8::
Local<v8::Object>, std::string)':
../src/serialport.cpp:17:1: warning: control reaches end of non-void function [-
Wreturn-type]
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory `/var/lib/cloud9/com.cea.smartmold.manual/node_modules/s
erialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_
modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Linux 3.8.13-bone79
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_mod
ules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/cloud9/com.cea.smartmold.manual/node_modules/serialport
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN pernoud-etooling-motor-command@0.0.1 No repository field.
npm WARN pernoud-etooling-motor-command@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.0.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@6.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-19T15_48_01_266Z-debug.log

**Comment by fivdi** [comment]
@sdhouib Was it possible to resolve this issue? I can't see anything in the output of the install process indicating what the error might be.

The command `npm install serialport` (without sudo) runs successfully for me on a BeagleBone Black in the same cloud9 directory with Debian 9.2 (cat /etc/debian_version) and a 4.4.91-ti-r133 kernel (uname -a):
```
debian@beaglebone:/var/lib/cloud9/com.cea.smartmold.manual$ node -v
v6.11.4
debian@beaglebone:/var/lib/cloud9/com.cea.smartmold.manual$ uname -a
Linux beaglebone 4.4.91-ti-r133 #1 SMP Tue Oct 10 05:18:08 UTC 2017 armv7l GNU/Linux
debian@beaglebone:/var/lib/cloud9/com.cea.smartmold.manual$ npm install serialport

> serialport@6.0.4 install /var/lib/cloud9/com.cea.smartmold.manual/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/serialport-v6.0.4-node-v48-linux-arm.tar.gz
prebuild-install info looking for cached prebuild @ /home/debian/.npm/_prebuilds/https-github.com-EmergingTechnologyAdvisors-node-serialport-releases-download-v6.0.4-serialport-v6.0.4-node-v48-linux-arm.tar.gz
prebuild-install http request GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v48-linux-arm.tar.gz
prebuild-install http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v48-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=6.11.4 runtime=node arch=arm platform=linux)
make: Entering directory '/var/lib/cloud9/com.cea.smartmold.manual/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/var/lib/cloud9/com.cea.smartmold.manual/node_modules/serialport/build'
/var/lib/cloud9/com.cea.smartmold.manual
└─┬ serialport@6.0.4 
  ├── bindings@1.3.0 
  ├── commander@2.12.2 
  ├─┬ debug@3.1.0 
  │ └── ms@2.0.0 
  ├── nan@2.8.0 
  ├─┬ prebuild-install@2.4.1 
  │ ├── expand-template@1.1.0 
  │ ├── github-from-package@0.0.0 
  │ ├── minimist@1.2.0 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ node-abi@2.1.2 
  │ │ └── semver@5.4.1 
  │ ├── noop-logger@0.1.1 
  │ ├─┬ npmlog@4.1.2 
  │ │ ├─┬ are-we-there-yet@1.1.4 
  │ │ │ ├── delegates@1.0.0 
  │ │ │ └─┬ readable-stream@2.3.3 
  │ │ │   ├── core-util-is@1.0.2 
  │ │ │   ├── inherits@2.0.3 
  │ │ │   ├── isarray@1.0.0 
  │ │ │   ├── process-nextick-args@1.0.7 
  │ │ │   ├── string_decoder@1.0.3 
  │ │ │   └── util-deprecate@1.0.2 
  │ │ ├── console-control-strings@1.1.0 
  │ │ ├─┬ gauge@2.7.4 
  │ │ │ ├── aproba@1.2.0 
  │ │ │ ├── has-unicode@2.0.1 
  │ │ │ ├── object-assign@4.1.1 
  │ │ │ ├── signal-exit@3.0.2 
  │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ ├── code-point-at@1.1.0 
  │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │   └── number-is-nan@1.0.1 
  │ │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ │ └── ansi-regex@2.1.1 
  │ │ │ └── wide-align@1.1.2 
  │ │ └── set-blocking@2.0.0 
  │ ├── os-homedir@1.0.2 
  │ ├─┬ pump@1.0.3 
  │ │ ├── end-of-stream@1.4.0 
  │ │ └─┬ once@1.4.0 
  │ │   └── wrappy@1.0.2 
  │ ├─┬ rc@1.2.2 
  │ │ ├── deep-extend@0.4.2 
  │ │ ├── ini@1.3.5 
  │ │ └── strip-json-comments@2.0.1 
  │ ├─┬ simple-get@1.4.3 
  │ │ └── unzip-response@1.0.2 
  │ ├─┬ tar-fs@1.16.0 
  │ │ ├── chownr@1.0.1 
  │ │ └─┬ tar-stream@1.5.5 
  │ │   └── bl@1.2.1 
  │ ├── tunnel-agent@0.6.0 
  │ └── xtend@4.0.1 
  ├── promirepl@1.0.1 
  └── safe-buffer@5.1.1 

npm WARN enoent ENOENT: no such file or directory, open '/var/lib/cloud9/com.cea.smartmold.manual/package.json'
npm WARN com.cea.smartmold.manual No description
npm WARN com.cea.smartmold.manual No repository field.
npm WARN com.cea.smartmold.manual No README data
npm WARN com.cea.smartmold.manual No license field.
debian@beaglebone:/var/lib/cloud9/com.cea.smartmold.manual$ 
```
