### ISSUE TITLE
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/serialport/build'

### ISSUE THREAD

**Issue by oleg-goodzon** [node-serialport/node-serialport#1499]
- __SerialPort Version__: 6.0.5
- __NodeJS Version__: 8.9.4
- __Operating System__ and __Hardware Platform__: LUBUNTU 16.04 ARM (OrangePI)

- Have you checked the right __version__ of the __api docs?__: Yes
- Are you having trouble installing and you checked the __Installation Special Cases__ docs? Yes
- Are you using __Electron__ and have you checked the _Electron Docs_?: Not using Electron

### Summary of Problem
Try to install serial port by command sudo npm install -g serialport
During installation receive message 
prebuild-install http 404 https://github.com/node-serialport/node-serialport/releases/download/v6.0.5/serialport-v6.0.5-node-v57-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.4 runtime=node arch=arm platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/serialport/build'
 But I run it under sudo!!!

### Steps and Code to Reproduce the Issue

**Comment by fivdi** [comment]
@oleg-goodzon please take a look at the [sudo/root section of the readme](https://github.com/node-serialport/node-serialport#sudo--root).

**Comment by fivdi** [comment]
The EACCES error most likely occurred because `--unsafe-perm` wasn't specified on the command line when `sudo npm install -g serialport` was called.

I don't think there's a TODO for serialport here so I'll go ahead and close the issue.
