### ISSUE TITLE
something wrong with serialport in my electron project

### ISSUE THREAD

**Issue by zhangshuaidan** [node-serialport/node-serialport#1597]
- __SerialPort Version__:6.2.1
- __NodeJS Version__:8.11.3
- __Operating System__ and __Hardware Platform__:win10 x64

- Have you checked the right __version__ of the __api docs?__:no
- Are you having trouble installing and you checked the __Installation Special Cases__ docs?no
- Are you using __Electron__ and have you checked the _Electron Docs_?:yes

### Summary of Problem
I make a project that with electron-serialport (https://github.com/johnny-five-io/electron-serialport),at first it run is ok.but when I add react  and babel into it, and start it ,there is some erors. what should I do to solve them? 
`app.bundle.js:14 Error: Could not locate the bindings file. Tried:
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\build\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\build\Debug\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\build\Release\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\out\Debug\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\Debug\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\out\Release\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\Release\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\build\default\serialport.node
 → C:\Users\user\Desktop\react+electron\seriaport+electron\electron-serialport\compiled\8.2.1\win32\x64\serialport.node`

 
### Steps and Code to Reproduce the Issue
heer is my code 
`    
import * as serialport from 'serialport'
serialport.list((err, ports) => {
      console.log('ports', ports);
      if (err) {
        document.getElementById('error').textContent = err.message
        return
      } else {
        document.getElementById('error').textContent = ''
      }
    
      if (ports.length === 0) {
        document.getElementById('error').textContent = 'No ports discovered'
      }

    })
    `

**Comment by Jozo132** [comment]
I got it kind-of working this way
`
const SerialPort = require('./node_modules/serialport/test.js');
const emulatedSerial = SerialPort.Binding;

emulatedSerial.createPort('COM-1', { echo: true, record: true })
const emulatedPort = new SerialPort('COM-1')

// This should return all ports + emulated port
const listPorts = () => {
    SerialPort.list(function (err, ports) {
        ports.forEach(function (port) {
            console.log(JSON.stringify(port));
        });
        if (err) console.log(err);
    });
}

listPorts();
`
