### ISSUE TITLE
Problem with raspberry pi 3+ and Arduino on NodeJS

### ISSUE THREAD

**Issue by Sousana9617** [node-serialport/node-serialport#1728]
With a friend, we are trying to build a program on a raspberry pi 3 B+ that is using a Arduino to function. It's working on his computer but since I've tested it on raspberry I've encourtered many problems. This is the last problem I've with it, I've past many days searching on Internet how to fix it, but there's nothing. Could you help me ?

Here are the screenshot : Thank you :)
![app](https://user-images.githubusercontent.com/15875537/48971658-f847b680-f01c-11e8-880e-aee82fe7bffe.png)
![terminal](https://user-images.githubusercontent.com/15875537/48971659-f847b680-f01c-11e8-8095-9f2f97f6797f.png)

**Comment by HipsterBrown** [comment]
@Sousana9617 Have you looked through the installation instructions for Serialport on Raspberry-Pi? https://serialport.io/docs/en/guide-installation#raspberry-pi-linux

From the screenshot, it appears the native bindings for node-serialport are not included in the electron build.

**Comment by Sousana9617** [comment]
Hello I've resolved my problem. Yes serialport was not good installed. Here's the solution
Installer serialport :

npm install –save-dev electron-rebuild
npm install serialport
$(npm bin)/electron-rebuild
npm install
npm start

I think it's not clear that I've to launch electron rebuild, for installing serialport in the documentation.

**Comment by HipsterBrown** [comment]
> I think it's not clear that I've to launch electron rebuild, for installing serialport in the documentation.

I'm glad you got it working. It's definitely a mixed case of the Electron and Raspberry PI installation instructions. Not sure how we would label the instructions for that but if you had a tutorial for us to share, we could add that to the docs. 

Happy hacking! :smile:
