### ISSUE TITLE
serialport does not work with Virtual COM on Windows 

### ISSUE THREAD

**Issue by huydox** [node-serialport/node-serialport#1744]
### Summary of Problem
I tried to get an example of reading data from COM port on Windows but no luck. There is no data emit on data event of serialport as well as parser.

(Please answer all 3)

- What are you trying to do?
Just read data from serialport.
- What happens?
No data got in data event of serialport or parser. 
If I stop code as read function of library in debug mode, and make data available before continue, data will be emitted.
After that, `end` event will be emit and no data can be receive after that.
- What should have happened?
I should get data whenever data come to my COM port
### Code to Reproduce the Issue

```js
const SerialPort = require('serialport');
const Readline = require('@serialport/parser-readline');
const port = new SerialPort('COM1', { 
    baudRate: 9600,
    dataBits: 8,
    parity: 'none',
    stopBits: 1,
    highWaterMark: 32,
    hupcl: false
});

parser = port.pipe(new Readline({delimiter: '\n', encoding:'utf8'}));

parser.on('data', function(data){
  console.log('parser data:', data);
})

port.on('data', data =>{
  console.log('got word from arduino:', data);
  console.log(data.toString());
});

port.on('error', (err) => {
  console.log('port err', err);
});

port.on('close', () => {
  console.log('port close');
})

port.on('end', () => {
  console.log('port end');
})

port.on('open', function(){
  console.log('port already open');
})
```
### Output
```
server>$env:DEBUG="*";node .\test.js
  serialport/stream opened path: COM1 +3ms
port already open
  serialport/stream _read reading +0ms
  serialport/binding-abstract read +13ms
  serialport/stream binding.read finished +2ms
  serialport/stream binding.read Zero bytes read closing readable stream +0ms
port end
server>
```
### Versions, Operating System and Hardware

- SerialPort@7.1
- Node.js v8.12
- Windows 10
- Hardware and chipset: ATC-1200 (Ethernet to Serial Converter)

**Comment by huydox** [comment]
I believe that issue come bindings.node (which built from C++).
In work case, if there is no data, bytesRead always return undefined and keep waiting for data.
In failed case, bytesRead returns 0 and stop waiting for data.

**Comment by HipsterBrown** [comment]
@huydox What are you using to create the virtual ports? Is the program called Virtual COM?

**Comment by huydox** [comment]
Hi @HipsterBrown,
I'm using this one - which included with ATC-1200

![2018-12-18_22-58-06](https://user-images.githubusercontent.com/970592/50166034-bc042f00-0318-11e9-9ca4-45691a9aac49.png)
 product

**Comment by HipsterBrown** [comment]
@huydox Can you run `npx @serialport/list` and see if your virtual port is listed?

**Comment by huydox** [comment]
Yes @HipsterBrown, list works and prints virtual port.
 I can also open virtual port success.
With my debug above by setting break point in read function, then send data to COM port, it can read data. However when it reads to EOF, there is a problem that cause the stream end and no longer wait for next data.
So I guest the problem some thing like read null data.

**Comment by HipsterBrown** [comment]
Thanks for the update, that's great to know. Happy building! 🎉
