### ISSUE TITLE
setTimeout and serialport interaction

### ISSUE THREAD

**Issue by cleoo** [node-serialport/node-serialport#1754]
Hi,

I'm trying to use a timer to evaluate if the device i'm using is still responding, with a code like that:

  [...]
  serial.write(**request**);
  dead_timer = setTimeout(() => { **set device is dead** }, 5000);
  
  
  [...]
  serial.on('data', **response** => {
  	clearTimeout(dead_timer);
  	[...]
  })

But the code don't work anymore as expected. The timer freeze the data event during 5000ms, unless I "deref" the timer object. Can someone explain this behavior ?

Ps: I'm using Linux Arch, node 11.5.0, latest serial port.

**Comment by Holger-Will** [comment]
See #1751
