### ISSUE TITLE
Communication breaks between raspberry pi 3 and arduino

### ISSUE THREAD

**Issue by DiPSoMaNiE** [node-serialport/node-serialport#1768]
### Summary of Problem

- What are you trying to do?

Read/write between a Raspberry pi 3 and an Arduino Uno R3 connected to one of the rpi usb port using node and the serialport library.

From the rpi, I write a command (1 char + \n) to the serialport. The arduino does some work according to the command, then a few seconds later (1 to 3s) writes on its Serial to answer the rpi (about 500 characters + \n).

- What happens?

After some write/read cycles (sometimes a few, sometimes for hours...), the serial communication breaks with the following error emitted from the serialport `close` event: `Error: bad file descriptor disconnected: true`.

I wrote some code using `setInterval` to automatically try to reconnect the serialport (making sure the port is closed using `port.isOpen`) but then get this error: `Error: No such file or directory, cannot open /dev/ttyUSB0`.

**I have to restart the node server for the port to be openable again and having the communication to work**, making me think that the arduino still works and is not the issue.

I've configured the usb bus of the rpi to use usb1.1 instead of usb2.0 (using the `dwc_otg.speed=1` parameter in `/boot/cmdline.txt`) but it didn't resolve the issue.

Given the following `syslog` dump from the rpi, it looks like the whole usb bus is crashing ?

```
rpi kernel: [60582.270462] usb usb1-port1: disabled by hub (EMI?), re-enabling...
rpi kernel: [60582.270480] usb 1-1: USB disconnect, device number 14
rpi kernel: [60582.270486] usb 1-1.1: USB disconnect, device number 15
rpi kernel: [60582.270672] smsc95xx 1-1.1:1.0 eth0: unregister 'smsc95xx' usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet
rpi kernel: [60582.270736] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
rpi dhcpcd[333]: eth0: removing interface
rpi kernel: [60582.310988] usb 1-1.2: USB disconnect, device number 17
rpi kernel: [60582.311269] usb 1-1.2: failed to send control message: -19
rpi kernel: [60582.311529] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
rpi kernel: [60582.311586] ch341 1-1.2:1.0: device disconnected
rpi kernel: [60582.510492] Indeed it is in host mode hprt0 = 00021501
rpi kernel: [60582.720444] usb 1-1: new full-speed USB device number 18 using dwc_otg
rpi kernel: [60582.720601] Indeed it is in host mode hprt0 = 00021501
rpi kernel: [60582.960618] usb 1-1: not running at top speed; connect to a high speed hub
rpi kernel: [60582.960804] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
rpi kernel: [60582.960810] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
rpi kernel: [60582.961284] hub 1-1:1.0: USB hub found
rpi kernel: [60582.961365] hub 1-1:1.0: 5 ports detected
rpi kernel: [60583.290415] usb 1-1.1: new full-speed USB device number 19 using dwc_otg
rpi kernel: [60583.420701] usb 1-1.1: not running at top speed; connect to a high speed hub
rpi kernel: [60583.420892] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
rpi kernel: [60583.420898] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
rpi kernel: [60583.423515] smsc95xx v1.0.6
rpi mtp-probe: checking bus 1, device 19: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1"
rpi mtp-probe: bus: 1, device: 19 was not an MTP device
rpi kernel: [60583.523799] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:7a:bf:6f
rpi kernel: [60583.620443] usb 1-1.2: new full-speed USB device number 20 using dwc_otg
rpi dhcpcd[333]: eth0: waiting for carrier
rpi kernel: [60583.672577] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
rpi kernel: [60583.672831] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
rpi kernel: [60583.761162] usb 1-1.2: New USB device found, idVendor=1a86, idProduct=7523
rpi kernel: [60583.761172] usb 1-1.2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
rpi kernel: [60583.761177] usb 1-1.2: Product: USB2.0-Serial
rpi kernel: [60583.761680] ch341 1-1.2:1.0: ch341-uart converter detected
rpi kernel: [60583.762153] usb 1-1.2: ch341-uart converter now attached to ttyUSB1
rpi mtp-probe: checking bus 1, device 20: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2"
rpi mtp-probe: bus: 1, device: 20 was not an MTP device
rpi node[32091]: 2019-01-08T13:20:03.055Z rpi:serial error { Error: bad file descriptor disconnected: true }
```

Since I've updated to Raspbian Stretch, most of the time it only takes a few read/write before breaking (but sometimes it can last for hours) whereas it was more like hours/days on Raspbian Jessie.

So I came here because I have no clue what is happening and am looking for some help from the community.

- What should have happened?

The communication should not break :(

### Code to Reproduce the Issue

```js
'use strict';
const SerialPort = require('serialport');

class Serial {
  constructor(path, rate = 19200) {
    this.path = path;
    this.rate = rate;
  }

  connect() {
    this.port = new SerialPort(this.path, {baudRate: this.rate});
    this.port.pipe(new SerialPort.parsers.Readline({delimiter: '\n'}));
    this.port.on('open', this.onOpen.bind(this));
    this.port.on('data', this.onData.bind(this));
    this.port.on('error', this.onError.bind(this));
    this.port.on('close', this.onError.bind(this));
  }

  write(data) {
    this.port.write(data + '\n');
  }

  onOpen() {
    // remove auto reconnect
    if (this.retryInterval) {
      clearInterval(this.retryInterval);
      this.retryInterval = undefined;
    }
    // start serial health checking
    setTimeout(() => {
      const checkInterval = setInterval(() => {
        const timeout = ... // true when last received data from arduino is too old
        if (timeout) {
          clearInterval(checkInterval);
          if (this.port.isOpen) this.port.close(null, {message: 'idle for too long'});
          else this.onError({message: 'idle for too long'});
        }
      }, CHECK_INTERVAL);
    }, CHECK_INTERVAL);
  }

  onData(data) {
    // do something with data
  }

  onError(err) {
    // auto reconnect
    if (!this.retryInterval) this.retryInterval = setInterval(this.connect.bind(this), RETRY_INTERVAL);
  }
}

const serial = new Serial('/dev/ttyUSB0').connect();
```

### Versions, Operating System and Hardware

- SerialPort@? **7.0.2**
- Node.js v? **8.15.0**
- Windows? Linux? Mac? **Raspbian Stretch (Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux)**
- Hardware and chipset? Raspberrypi 3 model B with 2.5A power supply, Arduino Uno R3 and a type A USB cable

**Comment by HipsterBrown** [comment]
@DiPSoMaNiE  can you try following the instructions in this comment? -> https://github.com/node-serialport/node-serialport/issues/1747#issuecomment-449456878

It appears to have resolved a similar issue.

**Comment by HipsterBrown** [comment]
Can you also try using the latest release of Serialport, version 7.1.2, to see if that helps at all?

**Comment by DiPSoMaNiE** [comment]
With the 7.1.2 version I get a `Segmentation fault` error when I try to open the port.
Looks like #1770 and #1771

**Comment by DiPSoMaNiE** [comment]
Searching for this kind of USB disconnection issues, some people reported it was due to a power supply issue or a bad USB cable.
As I also have devices powered by the 5V GPIO of the raspberry, I will check up on this lead for now.
