### ISSUE TITLE
data delay

### ISSUE THREAD

**Issue by thiagoanselmo** [node-serialport/node-serialport#1769]
SerialPort - 7.1.1
- Node.js  - 8.12
- Linux - Raspbian
- Hardware - RaspberryPI Zero W
- Serial - /dev/ttyS0

I will try to explain the scenario.

I have an arduino sending a 'raspberry test' information every 500ms. The problem happens, if I use serialport a delay in information starts, ussing babel (ES6)

Now file clean .js file I have no problems. 

##### code arduino
```c
#define SERIAL_BAUD_RATE         115200  

void setup() 
{
  startSerial();
  
}

void loop() {

 
 Serial1.print("<raspberry test>");
 delay(500);

}

void startSerial() 
{
  Serial.begin(SERIAL_BAUD_RATE);
  while (!Serial) {
    ;
  }

  Serial1.begin(SERIAL_BAUD_RATE);
  while (!Serial1) {
    ;
  }
}
```

#### file serialport  /lib
```javascript
import serialPort from 'serialport'
import delimiter from '@serialport/parser-delimiter'
import { serialport, serialBaudrate } from 'config'

export const port = new serialPort(serialport, {
  baudRate: serialBaudrate,
  autoOpen: false
})

export const parser = port.pipe(new delimiter({ delimiter: '>' }))

```
##### file index.js**
```javascript

import { port as clientSerial, parser as clientParseSerial } from './lib'
import generalFunctions from './controller'
	
clientSerial.open(function (err) {
  if (err) {
    console.log('Error opening port: ', err.message);
  }  
});

// Switches the port into "flowing mode"
clientParseSerial.on('data', function (data) {
  data = data.toString()
  data = data.replace(/[<>]/g, '')	  

  console.log('Received Serial:', data.trim(), generalFunctions.dateMsBrNow())
})

```

**ouput error data delay**

raspberry test 17-01-2019 12:04:35:288
raspberry test 17-01-2019 12:04:35:294
raspberry test 17-01-2019 12:04:35:300
raspberry test 17-01-2019 12:04:35:306
raspberry test 17-01-2019 12:04:35:312
raspberry test 17-01-2019 12:04:35:317
raspberry test 17-01-2019 12:04:35:323
raspberry test 17-01-2019 12:04:35:659
raspberry test 17-01-2019 12:04:36:105
raspberry test 17-01-2019 12:04:38:274
raspberry test 17-01-2019 12:04:38:280
raspberry test 17-01-2019 12:04:38:285
raspberry test 17-01-2019 12:04:38:291
raspberry test 17-01-2019 12:04:40:331
raspberry test 17-01-2019 12:04:40:337
raspberry test 17-01-2019 12:04:40:342
raspberry test 17-01-2019 12:04:40:348

##### File .js clean**
```javascript

const SerialPort = require('serialport')
const delimiter  = require('@serialport/parser-delimiter')
const generalFunctions = require('./controller')

const port = new SerialPort('/dev/ttyS0', { baudRate: 115200})

let parser = port.pipe(new delimiter({ delimiter: '>' }))

parser.on('data', line => {

	line = line.toString()
	line = line.replace(/[<>]/g, '')

	console.log(line, generalFunctions.dateMsBrNow())
})

```
##### output 500ms "NO ERROR"

raspberry test 17-01-2019 12:05:13:611
raspberry test 17-01-2019 12:05:14:112
raspberry test 17-01-2019 12:05:14:612
raspberry test 17-01-2019 12:05:15:112
raspberry test 17-01-2019 12:05:15:612
raspberry test 17-01-2019 12:05:16:113
raspberry test 17-01-2019 12:05:16:613
raspberry test 17-01-2019 12:05:17:113
raspberry test 17-01-2019 12:05:17:613
raspberry test 17-01-2019 12:05:18:113
raspberry test 17-01-2019 12:05:18:613
raspberry test 17-01-2019 12:05:19:114
raspberry test 17-01-2019 12:05:19:614
raspberry test 17-01-2019 12:05:20:114
raspberry test 17-01-2019 12:05:20:614
raspberry test 17-01-2019 12:05:21:114
raspberry test 17-01-2019 12:05:21:615
raspberry test 17-01-2019 12:05:22:115

**Comment by HipsterBrown** [comment]
> Only serialport and http (express) were no longer delayed

Can you clarify what you mean by that? If you only use serialport and http, then the code work?

**Comment by thiagoanselmo** [comment]
### The code under gives error, the delay happens

```javascript
var app = require('http').createServer()
var io = require('socket.io')(app);

const SerialPort = require('serialport')
const delimiter  = require('@serialport/parser-delimiter')
const port = new SerialPort('/dev/ttyS0', { baudRate: 115200})
let parser = port.pipe(new delimiter({ delimiter: '>' }))

parser.on('data', line => {
	line = line.toString()
	line = line.replace(/[<>]/g, '')
	io.emit('serialData', line);
})

app.listen(9090);

io.on('connection', function (socket) {  
  console.log('connect');  
});

```

**Comment by HipsterBrown** [comment]
After looking back at some past issues, I believe this an issue with Node.js (see https://github.com/node-serialport/node-serialport/issues/797#issuecomment-242537750). Basically, `socket.io` and `serialport` are using the same thread pool for the underlying async events, so when the pool has reached its limit then the pending "data" events are blocked until those threads are freed. That is why removing the usage of `socket.io` from your program fixes the issue. 

From the linked issue:

> It's not node-serialport, you can replace the serialport calls with fs.write and the same delay would happen. The root cause is that the network requests (actually the dns part), serialport, fs all use the same thread pool (default size=4)

**Comment by thiagoanselmo** [comment]
and a net library from the js node works with serial port?

**Comment by HipsterBrown** [comment]
It's not a direct issue with serialport or socket.io, it's how Node.js itself works. This will be an issue with any program that uses the filesystem and network requests at the same time. If you need to emit data every 500 ms, then you will run into delays on a lower-powered device like the Raspberry Pi.

**Comment by thiagoanselmo** [comment]
I will use 'wiringpi' to read the serial and send via socket
