### ISSUE TITLE
Payment protocol - RS232

### ISSUE THREAD

**Issue by bgnq** [node-serialport/node-serialport#1775]
Hello,

I can not implement a protocol to control a payment terminal in windows OS with the last version on serialport.
I attach specification and my code.
Connexion is OK but the write function do nothing.

Can you help me please.
Thank a lot !

My code : 
https://gist.github.com/bgnq/d0be0ce88c4d34cb7f940319da01fb06

Render with debug  : 
http://www.zupimages.net/viewer.php?id=19/02/mtf5.png

Protocol explication : 
http://www.zupimages.net/viewer.php?id=19/02/k9tg.png
http://www.zupimages.net/viewer.php?id=19/02/jwm4.png

**Comment by JBtje** [comment]
```js
myPort.write('ENQ');
```

You are writing the string ENQ to the device... but your protocol tells you to write the character with the name `ENQ`, which is written as 0x05.

https://en.wikipedia.org/wiki/ASCII

Just like "A" is the 'name' of the character represented by 0x41

tip: `myPort.write( 0x05 );` I assume that will work...

**Comment by bgnq** [comment]
Thanks!
If I try :
myPort.write( 0x05 );
I get error : string or buffer type for parameter of function write

Thank for your help

**Comment by Holger-Will** [comment]
`myPort.write(Buffer.from([0x05]);`

**Comment by bgnq** [comment]
Yes !
Thanks your everybody.
