### ISSUE TITLE
Error installing serialport to raspberry pi 3 B

### ISSUE THREAD

**Issue by MarcusMelconian** [node-serialport/node-serialport#1786]
I am currently in the process of a creating an Alexa controlled robot for a university project. Skipping the details of the project, I am trying to  npm install serialport in order to connect my pi to my server, I am given these errors (see attached images).

I have tried everything, please help!!

Overall am trying to get johnny-five raspi-io running on my pi, so that once my server receives a rest question it sends via websocked the commands to the pi

**Comment by MarcusMelconian** [comment]
![1](https://user-images.githubusercontent.com/41688922/51438689-4557aa00-1ca7-11e9-88b4-cb74df3ad596.png)
![2](https://user-images.githubusercontent.com/41688922/51438691-48529a80-1ca7-11e9-8b06-0d697ae10502.png)

**Comment by EscolanoGarnica** [comment]
Use this:
npm install serialport --unsafe-perm=true

**Comment by luisesn** [comment]
Seems to be a deprecation error: installing node v8 and installing serialport gives the following warning:
```

../src/serialport_unix.cpp:45:111: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   result->vtime = Nan::Get(options, Nan::New<v8::String>("vtime").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                          
```                                                     ^

**Comment by fivdi** [comment]
The first screenshot above shows that `npm install express` was run from the command line and that npm decided that it was necessary to install serialport v4.0.7. The second screenshot shows that Node.js v10.15.0 was used.

serialport v4.0.7 is very old and doesn't work with Node.js v10.15.0.

I'd suggest upgrading to the latest version of serialport.

**Comment by totovr** [comment]
Try with:

      sudo npm i serialport

For me worked:

![image](https://user-images.githubusercontent.com/15333235/52247546-a7faa800-292d-11e9-8fc5-acdf4849cb07.png)

**Comment by gganebnyi** [comment]
@MarcusMelconian are you using virtual serial port (https://www.npmjs.com/package/virtual-serialport) in your app?
