### ISSUE TITLE
encoding dose not support 'Unicode' or 'gbk' ?

### ISSUE THREAD

**Issue by XueYuSky** [node-serialport/node-serialport#1788]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?
Try to send string which is chinese. It is encoded in 'gbk' or in 'Unicode'
- What happens?
The parameters do not include these two encoding method. And string appeas garbled

### Code to Reproduce the Issue
just use myport.write() to send some chinese to another serialport.
```js
### Versions, Operating System and Hardware

- SerialPort@?
- Node.js v?
- Windows? Linux? Mac?
- Hardware and chipset? (Prolific/FTDI/Other)

**Comment by hanfengcan** [comment]
```
serialport.write(data: string|Buffer|Array<number>, encoding?: string, callback?: error => {}): boolean
```

try serialport.write(buffer, 'utf-8')
