### ISSUE TITLE
serialport makes devtools disconnected from the page.

### ISSUE THREAD

**Issue by wiener0zyj** [node-serialport/node-serialport#1791]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?
I'm tring to run the demo electron-serialport on win10. after i build and start up the electron. 
I get this this error: "devtools disconnected from the page" and nothing showing on the screen.
enviroment:
win10
electron 4.4.0
serialport  7.1.4

- What happens?
"devtools disconnected from the page"

- What should have happened?
I think the electron crashes! I could not decide what to do.

### Code to Reproduce the Issue

```js
const serialport = new SerialPort(path)
serialport.list(function(err, ports) {
        console.log(ports);
        });
// Code
```

### Versions, Operating System and Hardware

- SerialPort@? 7.1.4
- Node.js v? 10.15.0  x64
- Windows? Linux? Mac? Windows 10
- Hardware and chipset? (Prolific/FTDI/Other) did not connect to hardware

**Comment by wiener0zyj** [comment]
This blocks me for two days. I have rebuild the electron. but what ever codes about serialport  added would crashed electron. Too sad.
I have even tried to build from source code, still problems.
anyone has encountered the same problem? please give me a way.

**Comment by peteshand** [comment]
I'm having the same issue.
Electron 4.0.2
Node 11.11.0
Mac 10.14

I've rebuild from source. As soon as I call the serialport constructor with a path devtools disconnects

**Comment by aarshkd** [comment]
I was facing this issue before. I couldn't find the exact issue causing this but deleting everything related to electron(Locally and Globally) solved it. Try making a fresh install.

**Comment by peteshand** [comment]
similar story to me.. I got it working yesterday as well by deleting everything and then got it working with https://github.com/helloyan/electron-serialport and then transitioned over to this repo
